### ISSUE TITLE
TypeError: (0 , E.__experimentaluseLayoutClasses) is not a function

### ISSUE THREAD

**Issue by Ritvik-UX** [tomusborne/generatepress#465]
![errr](https://user-images.githubusercontent.com/73193822/199432848-05044338-7799-429f-8e19-be1b0887d09f.png)
```
TypeError: (0 , E.__experimentaluseLayoutClasses) is not a function
at Xt (https://website-name.com/queries/js/dist/edit-post.min.js:7:40200)
at ct (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:43430)
at os (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:111136)
at Ur (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:77643)
at Ir (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:77571)
at Dr (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:77434)
at Pr (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:74429)
at https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:30173
at unstable_runWithPriority (https://website-name.com/queries/js/dist/vendor/react.min.js:9:7431)
at xn (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:29950)
```

The Main Site is working! But, the editor is not working and show an “Attempt Block” option with Blank white Screen. When I click it, it doesn’t do anything.

What I’ve tried:
1. Updating All Plugins
2. Updating All Themes (On main site: GeneratePress)
3. Re-installing WordPress 6.1
4. Disable Browser Extensions
5. Restart All Process from Hosting

*Can’t share site’s name.
Thanks!

**Comment by Ritvik-UX** [comment]
Edit: After numerous refreshes, the error is not visible anymore in firefox dev!
I wasn't sure if its gutenberg-specific issue, so I opened another [issue in their repo](https://github.com/WordPress/gutenberg/issues/45479) too.

**Comment by tomusborne** [comment]
Hey @Ritvik-UX,

GP doesn't use `__experimentaluseLayoutClasses` anywhere in its code, so I don't believe the issue is on our end.

Your best bet is to disable the theme and your plugins one by one to find the problem code.
